#cloud-config

autoinstall:
    version: 1
    identity:
        realname: "Stephen Goncalves"
        hostname: ubuntu
        username: stgonzales
        password: "$6$MuMpQOK1qi1GyG.s$ZkZ3bCXYOy87sxXy0qvhv0yc.RtyiMHcgQI6SaXPeimyrcxeF7FnaufbGuRMTLOlBkmg3E4M7oUCk7aXwFgMr0"
    
    interactive-sections:
      - network
      - storage
    # storage:
    #   layout:
    #     name: lvm
    #     sizing-policy: all
    #     match:
    #       path: /dev/nvme0n1
    keyboard:
      layout: us
      variant: ""
    locale: en_GB
    timezone: "Europe/London"
    refresh-installer:
      update: true
      channel: latest/edge
    source:
      id: ubuntu-desktop
    apt:
      preserve_sources_list: false
      mirror-selection:
        primary:
          - country-mirror
          - uri: "http://archive.ubuntu.com/ubuntu"
            arches: [i386, amd64]
          - uri: "http://ports.ubuntu.com/ubuntu-ports"
            arches: [s390x, arm64, armhf, powerpc, ppc64el, riscv64]
      fallback: abort
      geoip: true
    ubuntu-pro:
      token: C12BRYHjXhCHzSpsqmnXQsVfdEojtg
    ssh:
      install-server: false
      authorized-keys: []
      allow-pw: true
    codecs:
      install: true
    drivers:
      install: true
    packages:
      - curl
      - git
      - polybar
      - flatpak
      - gnome-software-plugin-flatpak
      - zsh
    snaps:
      - name: discord
      - name: spotify
      - name: vscode
      - name: docker
      - name: ghostty
    updates: all
    shutdown: reboot
    late-commands:
      # i3
      - curtin in-target -- /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.03.09_all.deb keyring.deb SHA256:2c2601e6053d5c68c2c60bcd088fa9797acec5f285151d46de9c830aaba6173c
      - curtin in-target -- apt install ./keyring.deb
      - curtin in-target -- echo "deb [signed-by=/usr/share/keyrings/sur5r-keyring.gpg] http://debian.sur5r.net/i3/ $(grep '^VERSION_CODENAME=' /etc/os-release | cut -f2 -d=) universe" | sudo tee /etc/apt/sources.list.d/sur5r-i3.list
      # flatpak
      - curtin in-target -- flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      # zen browser
      - curtin in-target -- flatpak install flathub app.zen_browser.zen
      # Zsh default shell
      - curtin in-target -- chsh -s $(which zsh)
      # Oh My Zsh
      - curtin in-target -- sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      # spaceship
      - curtin in-target -- git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
      - curtin in-target -- ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
      # Github CLI
      - curtin in-target -- (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) && sudo mkdir -p -m 755 /etc/apt/keyrings && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg && sudo mkdir -p -m 755 /etc/apt/sources.list.d && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null && sudo apt update && sudo apt install gh -y
    error-commands:
      - tar -czf /installer-logs.tar.gz /var/log/installer
      - journalctl -b > /installer-journal.log
    kernel-crash-dumps:
      enabled: false