#cloud-config

autoinstall:
    version: 1
    identity:
        realname: "Stephen Goncalves"
        hostname: ubuntu
        username: stgonzales
        password: "$6$MuMpQOK1qi1GyG.s$ZkZ3bCXYOy87sxXy0qvhv0yc.RtyiMHcgQI6SaXPeimyrcxeF7FnaufbGuRMTLOlBkmg3E4M7oUCk7aXwFgMr0"
    
    interactive-sections:
      - network
      - storage
    keyboard:
      layout: us
      variant: ""
    locale: en_GB
    timezone: "Europe/London"
    refresh-installer:
      update: true
      channel: latest/edge
    source:
      id: ubuntu-desktop
    apt:
      preserve_sources_list: false
      mirror-selection:
        primary:
          - country-mirror
          - uri: "http://archive.ubuntu.com/ubuntu"
            arches: [i386, amd64]
          - uri: "http://ports.ubuntu.com/ubuntu-ports"
            arches: [s390x, arm64, armhf, powerpc, ppc64el, riscv64]
      fallback: abort
      geoip: true
    ubuntu-pro:
      token: C12BRYHjXhCHzSpsqmnXQsVfdEojtg
    ssh:
      install-server: false
      authorized-keys: []
      allow-pw: true
    codecs:
      install: true
    drivers:
      install: true
    packages:
      - curl
      - git
      - polybar
      - flatpak
      - gnome-software-plugin-flatpak
      - zsh
      - i3
      - feh
    snaps:
      - name: discord
      - name: spotify
      - name: code
        classic: true
      - name: docker
      - name: ghostty
    updates: all
    shutdown: reboot
    error-commands:
      - tar -czf /installer-logs.tar.gz /var/log/installer
      - journalctl -b > /installer-journal.log
    kernel-crash-dumps:
      enabled: false